version: '3.9'

services:
  web:
    build: .
    container_name: apache-php
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html
    networks:
      - red_app
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    

  db:
    image: mysql:5.7
    container_name: server-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: app_db
     
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - red_app

volumes:
  db_data:

networks:
  red_app: